---
# gaming-server Ceedling Project Configuration
# Ceedling test framework for gaming-server

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:tests/**
    - -:tests/support
  :source:
    - src/**
  :include:
    - src/**
    - ../gaming-core/src/**
  :support:
    - tests/support

:defines:
  # 在測試時定義 TESTING 宏
  :test:
    - TESTING
  :source:
    - TESTING

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

# 加入 Unity 配置
:unity:
  :use_param_tests: TRUE

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov

:flags:
  :test:
    :compile:
      :*:
        - -Wall
        - -Wextra
        - -Wno-unused-parameter
        - -std=c99
  :gcov:
    :compile:
      :*:
        - -g
        - -fprofile-arcs
        - -ftest-coverage
    :link:
      :*:
        - -fprofile-arcs
        - -ftest-coverage

:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []
  :test: []
  :release: []

# 設定測試 Runner 生成
:test_runner:
  :includes:
    - unity.h
  :file_suffix: _runner

# 設定工具路徑
:tools:
  :test_compiler:
    :executable: gcc
    :name: 'GCC Compiler'
    :arguments:
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -DGCOV_COMPILER
      - -c ${1}
      - -o ${2}
      - -Wall
      - -Wextra
      - -Wno-unused-parameter
      - -std=c99
      - -g
  
  :test_linker:
    :executable: gcc
    :name: 'GCC Linker'
    :arguments:
      - ${1}
      - -o ${2}
      - -lm
  
  :gcov_compiler:
    :executable: gcc
    :name: 'GCC Coverage Compiler'
    :arguments:
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -DGCOV_COMPILER
      - -fprofile-arcs
      - -ftest-coverage
      - -c ${1}
      - -o ${2}
      - -Wall
      - -Wextra
      - -std=c99
      - -g
  
  :gcov_linker:
    :executable: gcc
    :name: 'GCC Coverage Linker'
    :arguments:
      - -fprofile-arcs
      - -ftest-coverage
      - ${1}
      - -o ${2}
      - -lm

  :gcov_report:
    :executable: gcovr
    :optional: TRUE
    :arguments:
      - -r .
      - -e"vendor/.*"
      - -e"build/test/.*"
      - -e"tests/.*"
      - --html
      - --html-details
      - -o build/artifacts/gcov/GcovCoverageResults.html

# 文件生成配置
:module_generator:
  :project_root: ./
  :source_root: src/
  :test_root: tests/

...
