---
# Ceedling 1.0.1 Configuration for gaming-server
# 修正版本 - 支持 cJSON 库

:project:
  :name: gaming-server
  :build_root: build/
  :use_exceptions: FALSE
  :use_mocks: TRUE
  :compile_threads: 4
  :test_threads: 4

:release_build:
  :output: gaming-server.out
  :use_assembly: FALSE

:paths:
  :test:
    - +:tests/**
    - -:tests/support
  :source:
    - src/**
  :include:
    - src/**
    - ../gaming-core/src/**
  :support:
    - tests/support
  :libraries: []

:files:
  :test: []
  :source: []

:defines:
  :common: &common_defines
    - USE_HAL
  :test:
    - *common_defines
    - TEST
    - TESTING
    - UNITY_INCLUDE_DOUBLE
    - UNITY_DOUBLE_VERBOSE
  :test_preprocess:
    - *common_defines
    - TEST
    - TESTING
    - UNITY_INCLUDE_DOUBLE
    - UNITY_DOUBLE_VERBOSE

:flags:
  :test:
    :compile:
      :*:
        - -std=c99
        - -Wall
        - -Wextra
        - -Werror
        - -Wno-unused-parameter
    :link:
      :*: 
        - -lcjson  # 添加 cJSON 库链接

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :return_thru_ptr
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   HEX32
    int8:     INT8
    bool:     UINT8
    uint8_t:  HEX8
    uint16_t: HEX16
    uint32_t: HEX32
  :treat_as_void:
    - cec_event_callback_t
    - ps5_state_callback_t
    - ws_message_handler_t
    - ws_client_callback_t
    - server_state_callback_t
    - server_error_callback_t
  :callback_include_count: TRUE
  :callback_after_arg_check: FALSE

:gcov:
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
  :gcovr:
    :report_root: "."
    :report_exclude: "^build/|^tests/"
    :sort_percentage: TRUE
    :print_summary: TRUE
    :html_details: TRUE
    :html_medium_threshold: 75
    :html_high_threshold: 90

# 如果需要生成 XML 报告给 CI
:xml_tests_report:
  :artifact_filename: report.xml

:plugins:
  :enabled:
    #- stdout_pretty_tests_report
    - module_generator
    - gcov

# 环境变量（可选）
:environment: []

# 如果 cJSON 库不在标准路径，可以添加库路径
:libraries:
  :placement: :end
  :flag: "${1}"  # 使用 GCC/Clang 风格的链接标志
  :test: []
  :release: []
  :system:
    - cjson  # 系统库

# Test 前置处理器（如果需要）
:test_build:
  :use_assembly: FALSE
